name: tabbar_gradient_indicator_plus
description: A Flutter tabbar gradient indicator support set the fixedWidth and direction of gradient. Writted with pure dart, supported both iOS and Android.
version: 1.0.1
homepage: https://github.com/ahyangnb/tabbar_gradient_indicator_plus

environment:
  sdk: '>=2.17.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0